# Spring
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/officialaccount?createDatabaseIfNotExist=true
    username: sa
    password: Welcome1
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false

# Server
server:
  port: 80